### ISSUE TITLE
Strange uci option values range

### ISSUE THREAD

**Issue by amchess** [joergoster/Stockfish#1]
[https://github.com/joergoster/Stockfish/blob/12f245167402d6ea777777c1b9a6b215ba1cc980/src/ucioption.cpp](https://github.com/joergoster/Stockfish/blob/12f245167402d6ea777777c1b9a6b215ba1cc980/src/ucioption.cpp)
In my opinion, the uci option o["LMReduction"] << Option(10, 0, 20) must be (10,0,10) because the r value can't be more than the default and it's a non sense to set it like this.

**Comment by joergoster** [comment]
Please note, you're commenting on a stale branch.
At that time I was a bit experimenting.

**Comment by amchess** [comment]
I was simply interested in this uci option.
So, can you confirm I'm right?
For the rest, surely I appreciate a lot your work!
Best regards,
Andrea

**Comment by joergoster** [comment]
Yes, you're right.

**Comment by amchess** [comment]
> 
> 
> Yes, you're right.

Many thanks!

Andrea
