### ISSUE TITLE
Prisoners' Chess not working as expected

### ISSUE THREAD

**Issue by lucrus73** [joergoster/Stockfish#2]
Hello Jörg, I open a new issue here, because I feel it's more appropriate now than keep commenting on the closed one of official Stockfish.

I've tested your code with the following FEN position:

`4k3/6Q1/7R/6B1/7p/7P/1p1P1PKP/8 w - - 0 1`

which is exactly the third example in the [PC variant description](https://www.chess.com/forum/view/chess960-chess-variants/prisoners-chess). I used XBoard and let your Stockfish PC branch play against itself (Two machines mode). I expected white PC to force black PC pawn promotion, in order to gain more points, but I'm afraid it does not work as intended yet, because it immediately opted for `Re6#` mate in one instead.

**Comment by lucrus73** [comment]
Yes, you are missing the fact that if White avoids the mate in one, Black has only one possible move, e.g. promoting its B pawn, because neither the H pawn nor the king can move anywhere.

**Comment by joergoster** [comment]
Thanks! Now it's clear. (I overlooked the bishop on g5!)
I will look into this asap. My first guess is either a bug, or it has something to do with (NOT) generating underpromotions.

**Comment by lucrus73** [comment]
Underpromotions are not the problem, because White must not mate regardless of the type of promotion Black will choose. Even better, if Black promotes to Queen, it's even better for White.

**Comment by joergoster** [comment]
In this position `3k2r1/R7/8/8/8/5KQ1/8/8 w - - 0 1` it correctly goes for Qb8# and not for Qxg8#.

> info depth 1 seldepth 2 multipv 1 score mate 1 nodes 118 nps 59000 tbhits 0 time 2 pv g3b8

**Comment by joergoster** [comment]
It looks like the mate distance pruning code is responsible for this.
Without it:
```
position fen 4k3/6Q1/7R/6B1/7p/7P/1p1P1PKP/8 w - - 0 1
go depth 24
info depth 1 seldepth 2 multipv 1 score mate 1 nodes 104 nps 52000 tbhits 0 time 2 pv h6e6
info depth 2 seldepth 2 multipv 1 score mate 1 nodes 162 nps 81000 tbhits 0 time 2 pv h6e6
info depth 3 seldepth 2 multipv 1 score mate 1 nodes 203 nps 101500 tbhits 0 time 2 pv h6e6
info depth 4 seldepth 2 multipv 1 score mate 1 nodes 244 nps 122000 tbhits 0 time 2 pv h6e6
info depth 5 seldepth 2 multipv 1 score mate 1 nodes 302 nps 151000 tbhits 0 time 2 pv h6e6
info depth 6 seldepth 2 multipv 1 score mate 1 nodes 482 nps 241000 tbhits 0 time 2 pv h6e6
info depth 7 seldepth 2 multipv 1 score mate 1 nodes 587 nps 293500 tbhits 0 time 2 pv h6e6
info depth 8 seldepth 4 multipv 1 score mate 2 nodes 650 nps 325000 tbhits 0 time 2 pv g5h4 b2b1b h6e6
info depth 9 seldepth 4 multipv 1 score mate 2 nodes 872 nps 436000 tbhits 0 time 2 pv g5h4 b2b1b h6e6
info depth 10 seldepth 4 multipv 1 score mate 2 nodes 1181 nps 590500 tbhits 0 time 2 pv d2d3 b2b1b h6e6
info depth 11 seldepth 4 multipv 1 score mate 2 nodes 2895 nps 965000 tbhits 0 time 3 pv d2d3 b2b1b h6e6
info depth 12 seldepth 4 multipv 1 score mate 2 nodes 5026 nps 1256500 tbhits 0 time 4 pv d2d3 b2b1b h6e6
info depth 13 seldepth 4 multipv 1 score mate 2 nodes 7156 nps 1431200 tbhits 0 time 5 pv d2d3 b2b1b h6e6
info depth 14 seldepth 4 multipv 1 score mate 2 nodes 10103 nps 1443285 tbhits 0 time 7 pv d2d3 b2b1b h6e6
info depth 15 seldepth 4 multipv 1 score mate 2 nodes 19768 nps 1797090 tbhits 0 time 11 pv d2d3 b2b1b h6e6
info depth 16 seldepth 4 multipv 1 score mate 2 nodes 32662 nps 1921294 tbhits 0 time 17 pv d2d3 b2b1b h6e6
info depth 17 seldepth 4 multipv 1 score mate 2 nodes 47809 nps 1992041 tbhits 0 time 24 pv d2d3 b2b1b h6e6
info depth 18 seldepth 4 multipv 1 score mate 2 nodes 104808 nps 2055058 tbhits 0 time 51 pv d2d3 b2b1b h6e6
info depth 19 seldepth 4 multipv 1 score mate 2 nodes 167849 nps 2072209 tbhits 0 time 81 pv d2d3 b2b1b h6e6
info depth 20 seldepth 4 multipv 1 score mate 2 nodes 249058 nps 2075483 tbhits 0 time 120 pv d2d3 b2b1b h6e6
info depth 21 seldepth 4 multipv 1 score mate 2 nodes 346495 nps 2062470 tbhits 0 time 168 pv d2d3 b2b1b h6e6
info depth 22 seldepth 4 multipv 1 score mate 2 nodes 543328 nps 2042586 tbhits 0 time 266 pv d2d3 b2b1b h6e6
info depth 23 seldepth 4 multipv 1 score mate 2 nodes 1019329 nps 2046845 tbhits 0 time 498 pv d2d3 b2b1b h6e6
info depth 24 seldepth 4 multipv 1 score mate 2 nodes 1611340 nps 2047445 tbhits 0 time 787 pv d2d3 b2b1b h6e6
bestmove d2d3 ponder b2b1b
```

**Comment by joergoster** [comment]
@lucrus73 Just updated my repo. It seems you were absolutely right about deactivating mate-distance pruning initially. ;-)
