### ISSUE TITLE
code repeated ?

### ISSUE THREAD

**Issue by MichaelB7** [joergoster/Stockfish#3]
in NNUE always  - in search.cpp you have  code at line 942 repeated at line 959 - not sure if that is intentional or not ...
```
    // Damp down the evaluation linearly when shuffling
    v = v * (100 - pos.rule50_count()) / 100;
```

**Comment by joergoster** [comment]
Good catch! It's an oversight. Thank you, Mike.
This part of the code will soon change, however, as I want to let the specialized endgames also kick in when using the NNUE.
