### ISSUE TITLE
uct branch cannot be compiled

### ISSUE THREAD

**Issue by Zerbinati** [joergoster/Stockfish#7]
Hi Jörg,
`search.cpp:1854:24: error: 'REWARD_LOSS' was not declared in this scope
 1854 |             bestUCB1 = REWARD_LOSS;
      |                        ^~~~~~~~~~~
search.cpp:1862:25: error: 'rootC' was not declared in this scope
 1862 |                       + rootC * std::sqrt(std::log(uctTable[currentIndex].N()) / uctTable[idx].N());`

**Comment by joergoster** [comment]
Code is not ready yet ...

**Comment by microsmeta** [comment]
Sorry, I can't reach you other ways:

Date: Sun, 6 Mar 2022 11:45:31 +0100
Subject: Full Alemo64Chess data removal from Outskirt Forum

Please,

could you remove ALL my sensible data: 

ACCOUNT, POSTS, COMMENTS, QUOTES, LIKES, LINKS, REFERRALS from your site?

Best Regards, Alex
